heartphoria/blueprints/appointment.py
from datetime import datetime

from flask import Blueprint, g, render_template, request, url_for, redirect

from heartphoria import db, redirect
from heartphoria.models import Appointment, Hospital
from heartphoria.blueprints.auth import login_required

blueprint = Blueprint('appointment', __name__, url_prefix='/appointment')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
    date = None
    time = None
    date_time = None
    location = None
    errors = {}

    if request.method == 'POST':
        delete = request.form.get('delete')

        if delete:
            appointment = Appointment.query.get(delete)
            db.session.delete(appointment)
            db.session.commit()
        else:
            date = request.form.get('date')
            time = request.form.get('time')
            location = request.form.get('location')

            if not (date and time):
                if not date:
                    errors['date'] = 'Date is required.'

                if not time:
                    errors['time'] = 'Time is required.'
            else:
                date_time = datetime.strptime(date + ' ' + time, '%Y-%m-%d %H:%M')

            if not location:
                errors['location'] = 'Location is required.'

            if not errors:
                appointment = Appointment(user_id=g.user['id'], date_time=date_time, location=location) #create appointment object with user input value
                db.session.add(appointment)
                db.session.commit()

                return redirect(url_for('.index'))

    appointments = Appointment.query.filter_by(user_id=g.user['id']).order_by(Appointment.date_time.desc()).all() #retrieve all appointment data based on user id
    hospitals = Hospital.query.with_entities(Hospital.name).all()

    return render_template('appointment/index.html', date=date, time=time, location=location, errors=errors, appointments=appointments, autocomplete=hospitals)

heartphoria/blueprints/history.py
from datetime import datetime

from flask import Blueprint, g, render_template, request

from heartphoria import db
from heartphoria.models import History
from heartphoria.blueprints.auth import login_required

blueprint = Blueprint('history', __name__, url_prefix='/history')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
    date = None
    description = None
    errors = {}

    if request.method == 'POST':
        delete = request.form.get('delete')

        if delete:
            history = History.query.get(delete)
            db.session.delete(history)
            db.session.commit()
        else:
            date = request.form.get('date')
            description = request.form.get('description')

            if not date:
                errors['date'] = 'Date is required.'

            if not description:
                errors['description'] = 'Description is required.'

            if not errors:
                history = History(user_id=g.user['id'], date=datetime.strptime(date, '%Y-%m-%d').date(), description=description)
                db.session.add(history)
                db.session.commit()

    histories = History.query.filter_by(user_id=g.user['id']).order_by(History.date.desc()).all()

    return render_template('history/index.html', title='Medical History', date=date, description=description, errors=errors, histories=histories)

heartphoria/blueprints/reminder.py
from datetime import datetime

from flask import Blueprint, g, render_template, request, url_for

from heartphoria import db, redirect
from heartphoria.models import Reminder
from heartphoria.blueprints.auth import login_required

blueprint = Blueprint('reminder', __name__, url_prefix='/reminder')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
    time = None
    medication = None
    quantity = None
    errors = {}

    if request.method == 'POST':
        delete = request.form.get('delete')

        if delete:
            reminder = Reminder.query.get(delete)
            db.session.delete(reminder)
            db.session.commit()

            return redirect(url_for('.index'))
        else:
            time = request.form.get('time')
            medication = request.form.get('medication')
            quantity = request.form.get('quantity')

            if not time:
                errors['time'] = 'Time is required.'
            else:
                time = datetime.strptime(time, '%H:%M').time().isoformat()

            if not medication:
                errors['medication'] = 'Medication is required.'

            if not quantity:
                errors['quantity'] = 'Quantity is required.'

            if not errors:
                reminder = Reminder(user_id=g.user['id'], time=datetime.strptime(time, '%H:%M:%S').time(), medication=medication, quantity=quantity)
                db.session.add(reminder)
                db.session.commit()

                return redirect(url_for('.index'))

    reminders = Reminder.query.filter_by(user_id=g.user['id']).all()

    return render_template('reminder/index.html', title='Medication Reminder', time=time, medication=medication, quantity=quantity, errors=errors, reminders=reminders)

heartphoria/blueprints/user.py
import re
import os
from datetime import datetime

import requests
from flask import Blueprint, g, render_template, request, url_for
from werkzeug.security import generate_password_hash

from heartphoria import app, db, ngrok_url, redirect
from heartphoria.models import User, Appointment, Reminder, History
from heartphoria.mail import Mail
from heartphoria.blueprints.auth import login_required

blueprint = Blueprint('user', __name__, url_prefix='/user')


@blueprint.route('/<int:user_id>')
@login_required
def index(user_id):
    image = None

    if g.user['id'] != user_id and g.user['role'] != 'admin':
        return redirect(url_for('general.index'))

    try:
        # Check if users profile picture exists when hosted with ngrok and on local.
        if requests.get(ngrok_url + '/static/images/dp/%s.png' % g.user['id'], timeout=1).status_code == 200 or \
                requests.get(request.url_root + 'static/images/dp/%s.png' % g.user['id'], timeout=1).status_code == 200:
            image = url_for('static', filename='images/dp/%s.png' % g.user['id']) + '?v=%s' % datetime.now().time()
    except requests.exceptions.ConnectionError:
        print('User has not uploaded any profile picture...')
    except requests.exceptions.RequestException as e:
        print(e)

    bmi = {
        'index': None if g.user['weight'] == 0 or g.user['height'] == 0 else round(g.user['weight'] / (g.user['height'] / 100 * g.user['height'] / 100))
    }

    if bmi['index']:
        if bmi['index'] >= 27.5:
            bmi['text'] = 'HIGH RISK'
        elif bmi['index'] >= 23:
            bmi['text'] = 'MODERATE RISK'
        elif bmi['index'] >= 18.5:
            bmi['text'] = 'LOW RISK'
        else:
            bmi['text'] = 'Risk Of Nutritional Deficiency'

    reminders = Reminder.query.filter_by(user_id=user_id).order_by(Reminder.time).limit(10).all()
    appointments = Appointment.query.filter_by(user_id=user_id).order_by(Appointment.date_time.desc()).limit(10).all()
    histories = History.query.filter_by(user_id=user_id).order_by(History.date.desc()).limit(10).all()

    return render_template('user/index.html', title=g.user['name'], reminders=reminders, appointments=appointments, histories=histories, bmi=bmi, image=image)


@blueprint.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    image = None
    name = None
    gender = None
    dob = None
    height = None
    weight = None
    email = None
    errors = {}

    try:
        # Check if users profile picture exists when hosted with ngrok and on local.
        if requests.get(ngrok_url + '/static/images/dp/%s.png' % g.user['id'], timeout=1).status_code == 200 or \
                requests.get(request.url_root + 'static/images/dp/%s.png' % g.user['id'], timeout=1).status_code == 200:
            image = url_for('static', filename='images/dp/%s.png' % g.user['id']) + '?v=%s' % datetime.now().time()
    except requests.exceptions.ConnectionError:
        print('User has not uploaded any profile picture...')
    except requests.exceptions.RequestException as e:
        print(e)

    if request.method == 'POST':
        if 'file' in request.files:
            file = request.files['file']

            if '.' in file.filename and file.filename.rsplit('.', 1)[1].lower() in ['png', 'jpg', 'jpeg']:
                file.save(os.path.join(app.config['UPLOAD_FOLDER'] + str(g.user['id']) + '.png'))

            return redirect(url_for('.edit'))
        elif request.form.get('remove'):
            os.remove(os.path.join(app.config['UPLOAD_FOLDER'] + str(g.user['id']) + '.png'))

            return redirect(url_for('.index', user_id=g.user['id']))
        else:
            name = request.form.get('name')
            gender = request.form.get('gender')
            dob = request.form.get('dob')
            height = request.form.get('height')
            weight = request.form.get('weight')
            email = request.form.get('email')
            password = request.form.get('password')
            confirm = request.form.get('confirm')
            data = {}

            if name:
                if not re.match(r'[a-zA-Z]+(?:\s[a-zA-Z]+)*$', name):
                    errors['name'] = 'Name is invalid'
                else:
                    data['name'] = name

            if gender:
                data['gender'] = gender
            else:
                errors['gender'] = 'Gender is required'

            if dob:
                try:
                    data['dob'] = datetime.strptime(dob, '%Y-%m-%d').date()
                except ValueError:
                    errors['dob'] = 'Invalid date format'

            if height:
                data['height'] = height

            if weight:
                data['weight'] = weight

            if email:
                if not re.match(r"[a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", email):
                    errors['email'] = 'Email address is invalid.'
                elif g.user['email'] != email and not User.query.filter_by(email=email).first() is not None:
                    errors['email'] = email + ' already exists'
                else:
                    data['email'] = email.lower()

            if password:
                if not re.match(r'(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$', password):
                    errors['password'] = 'Password is invalid'
                elif not confirm:
                    errors['confirm'] = 'Please re-enter password for confirmation'
                elif not password == confirm:
                    errors['confirm'] = 'Passwords do not match'
                else:
                    data['password'] = generate_password_hash(password)

            if not errors:
                if (not name or name == g.user['name']) and \
                        (not gender or gender == g.user['gender']) and \
                        (not dob or dob == str(g.user['dob'])) and \
                        (not height or height == str(g.user['height'])) and \
                        (not weight or weight == str(g.user['weight'])) and \
                        (email == g.user['email']):
                    errors['all'] = 'Nothing to update'
                else:
                    if User.query.filter_by(id=g.user['id']).first() is not None:
                        User.query.filter_by(id=g.user['id']).update(data)
                        db.session.commit()

                    Mail().send_mail(
                        [g.user['email'], email] if email else g.user['email'],
                        '[Heartphoria] Account Details Changed',
                        render_template('email/edit.html', name=name, gender=gender, dob=dob, height=height, weight=weight, email=email, password=password)
                    )

                    user = User.query.filter_by(id=g.user['id']).first()

                    if user:
                        user = user.__dict__

                        if '_sa_instance_state' in user:
                            del user['_sa_instance_state']

                        g.user = user

                    return redirect(url_for('.index', user_id=g.user['id']))

    return render_template('user/edit.html', title='Edit Profile', name=name, gender=gender, dob=dob, height=height, weight=weight, email=email, errors=errors, image=image)

heartphoria/templates/user/edit.html
{% extends 'base.html' %}

{% block content %}
    <section id="EditProfileSection">
        <form class="text-left" method="post" novalidate>
            <div class="row mb-3">
                <div class="col-12 text-right">
                    <button type="submit" class="btn acrylic btn-outline-success mr-2">Save</button>
                    <a class="btn acrylic btn-outline-danger shadow" href="{{ url_for('.index', user_id=g.user['id']) }}">Cancel</a>
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-4">
                    <div class="card acrylic-60 shadow-lg">
                        <div class="card-body text-center">
                            <div class="shadow mb-3 dp" data-toggle="modal" data-target="#UploadModal" style="background-image: url({{ image if image else url_for('static', filename='images/dp/default.png') }});">
                                <div class="text-white db-popup d-none">
                                    Change Profile Photo
                                </div>
                            </div>

                            {% if image %}
                                <button class="btn btn-danger btn-block mb-4" type="submit" name="remove" value="dp">
                                    Remove Profile Photo
                                </button>
                            {% endif %}

                            <div class="form-label-group text-left">
                                <input id="name" class="form-control{{ ' is-invalid' if errors['name'] or errors['all'] }}" type="text" placeholder="Name" name="name" value="{{ name or g.user['name'] }}" />
                                <label for="name">Name</label>
                                {% if errors['name'] or errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] if errors['all'] else errors['name'] }}</div>
                                {% endif %}
                            </div>

                            <div class="form-label-group">
                                <select class="form-control{{ ' is-invalid' if errors['gender'] or errors['all'] }}" name="gender">
                                    <option {{ 'selected ' if not gender or not g.user['gender'] }}disabled>Gender (Required)</option>
                                    <option value="Male" {{ ' selected' if gender == 'Male' or g.user['gender'] == 'Male' }}>Male</option>
                                    <option value="Female" {{ ' selected' if gender == 'Female' or g.user['gender'] == 'Female' }}>Female</option>
                                </select>
                                {% if errors['gender'] or errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] if errors['all'] else errors['gender'] }}</div>
                                {% endif %}
                            </div>

                            <div class="form-label-group text-left">
                                <input id="dob" class="form-control{{ ' is-invalid' if errors['all'] }}" type="date" placeholder="Date Of Birth" name="dob"{% if dob or g.user['dob'] %} value="{{ dob or g.user['dob'] }}"{% endif %} />
                                <label for="dob">Date Of Birth</label>
                                {% if errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] }}</div>
                                {% endif %}
                            </div>

                            <div class="form-label-group text-left">
                                <input id="height" class="form-control{{ ' is-invalid' if errors['all'] }}" type="number" placeholder="Height (cm)" name="height"{% if height or g.user['height'] %} value="{{ height or g.user['height'] }}"{% endif %} />
                                <label for="height">Height (cm)</label>
                                {% if errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] }}</div>
                                {% endif %}
                            </div>

                            <div class="form-label-group text-left">
                                <input id="weight" class="form-control{{ ' is-invalid' if errors['all'] }}" type="number" placeholder="Weight (kg)" name="weight"{% if weight or g.user['weight'] %} value="{{ weight or g.user['weight'] }}"{% endif %} />
                                <label for="weight">Weight (kg)</label>
                                {% if errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] }}</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-8 mt-4 mt-md-0">
                    <div class="card acrylic-60 shadow-lg">
                        <div class="card-body text-left">
                            <h4 class="pb-4 text-primary">Account Information</h4>

                            <div class="form-label-group">
                                <input id="email" class="form-control{{ ' is-invalid' if errors['email'] or errors['all'] }}" type="email" placeholder="Email" name="email" value="{{ email or g.user['email'] }}" />
                                <label for="email">Email</label>
                                {% if errors['email'] or errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] if errors['all'] or errors['email'] }}</div>
                                {% endif %}
                            </div>

                            <hr/>

                            <div class="form-label-group">
                                <input id="password" class="form-control{{ ' is-invalid' if errors['password'] or errors['all'] }}" type="password" placeholder="Password" name="password" />
                                <label for="password">Password</label>
                                {% if errors['email'] or errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] if errors['all'] else errors['password'] }}</div>
                                {% endif %}
                            </div>
                            <div class="form-label-group">
                                <input id="confirm" class="form-control{{ ' is-invalid' if errors['confirm'] or errors['all'] }}" type="password" placeholder="Confirm password" name="confirm" />
                                <label for="confirm">Confirm password</label>
                                {% if errors['confirm'] or errors['all'] %}
                                    <div class="feedback invalid-tooltip fadeIn">{{ errors['all'] if errors['all'] else errors['confirm'] }}</div>
                                {% endif %}
                                <small class="form-text">
                                    At least 8 characters and contains 1 numeric, upper and lowercase.
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </section>
{% endblock %}

{% block modal %}
<div id="UploadModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content acrylic-80">
            <div class="modal-header">
                <h4 class="text-primary">Upload Profile Photo</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <p class="small text-center">
                    It is recommended to upload a square image at 150 x 150.<br />
                    You are allowed to upload a file size of up to 2mb.<br />
                    Only .png, .jpg and .jpeg file types are allowed.
                </p>

                <div id="DragDropArea"></div>

                <form id="UploadForm" method="post" enctype="multipart/form-data">
                    <input class="d-none" accept="image/png, image/jpg, image/jpeg" type="file" name="file" />
                </form>
                <div class="feedback small text-danger text-center mt-2 d-none"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

heartphoria/templates/user/index.html
{% extends 'base.html' %}

{% block content %}
    <section id="ProfileSection">
        <div class="row mb-3">
            <div class="col-12 text-right">
                <a class="btn acrylic btn-outline-primary" href="{{ url_for('.edit') }}">Edit Profile</a>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="card acrylic-60 shadow-lg">
                    <div class="card-body text-center">
                        <img class="img-fluid shadow dp" src="{{ image if image else url_for('static', filename='images/dp/default.png') }}">

                        <h3 class="text-primary mt-4">{{ g.user['name'] }}</h3>

                        <hr />
                        {% if g.user.gender %}
                            <h6>Gender</h6>
                            <h4 class="text-primary">{{ g.user['gender'] }}</h4>

                            <hr />
                        {% endif %}

                        {% if g.user.dob %}
                            <h6>Date Of Birth</h6>
                            <h4 class="text-primary">{{ g.user['dob'].strftime('%d/%m/%Y') if g.user['dob'] }}</h4>

                            <hr />
                        {% endif %}

                        {% if g.user.height %}
                            <h6>Height</h6>
                            <h4 class="text-primary">
                                {{ g.user['height'] }} cm
                            </h4>

                            <hr />
                        {% endif %}

                        {% if g.user.weight %}
                            <h6>Weight</h6>
                            <h4 class="text-primary">{{ g.user['weight'] }} kg</h4>
                        {% endif %}
                    </div>
                </div>

                {% if bmi['index'] and bmi['text'] %}
                    <div class="card acrylic-60 shadow-lg mt-5">
                        <div class="card-body text-center">
                            <h4 class="pb-3 text-primary">BMI</h4>

                            <h4 class="text-primary">{{ bmi['index'] }}</h4>
                            <h6 class="text-muted">You are at <span class="text-primary text-uppercase font-weight-bold">{{ bmi['text'] }}</span></h6>
                        </div>
                    </div>
                {% endif %}

                <div class="card acrylic-60 shadow-lg mt-5">
                    <div class="card-body text-center">
                        <h4 class="pb-4 text-primary">Account Information</h4>

                        <h6>Email</h6>
                        <p class="text-primary">{{ g.user['email'] }}</p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-8 mt-4 mt-md-0">
                <div class="card acrylic-60 text-center shadow-lg">
                    <div class="card-header">
                        <ul class="nav nav-pills nav-fill card-header-pills">
                            <li class="nav-item">
                                <a class="nav-link active" href="#MedReminder" data-toggle="pill">Medication Reminder</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#MedAppointment" data-toggle="pill">Medical Appointment</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#MedHistory" data-toggle="pill">Medical History</a>
                            </li>
                        </ul>
                    </div>

                    <div class="card-body">
                        <div class="tab-content">
                            <div class="tab-pane active" id="MedReminder" role="tabpanel">
                                {% if reminders %}
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th scope="col">Time</th>
                                                <th scope="col">Medication</th>
                                                <th scope="col">Quantity</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for reminder in reminders %}
                                                <tr>
                                                    <td>{{ reminder['time'].strftime('%I:%m %p') }}</td>
                                                    <td>{{ reminder['medication'] }}</td>
                                                    <td>{{ reminder['quantity'] }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                    <a class="btn btn-info btn-block" href="{{ url_for('reminder.index') }}">View More</a>
                                {% else %}
                                    <h6>You do not have any Medication Reminder Yet.</h6>
                                {% endif %}
                            </div>

                            <div class="tab-pane" id="MedAppointment" role="tabpanel">
                                {% if appointments %}
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th scope="col">Date</th>
                                                <th scope="col">Time</th>
                                                <th scope="col">Hospital / Clinic</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for appointment in appointments %}
                                                <tr>
                                                    <td>{{ appointment['date_time'].strftime('%d/%m/%Y') }}</td>
                                                    <td>{{ appointment['date_time'].strftime('%I:%M %p') }}</td>
                                                    <td>{{ appointment['location'] }}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                    <a class="btn btn-info btn-block" href="{{ url_for('appointment.index') }}">View More</a>
                                {% else %}
                                    <h6>You do not have any Medical Appointment Yet.</h6>
                                {% endif %}
                            </div>

                            <div class="tab-pane" id="MedHistory" role="tabpanel">
                            {% if histories %}
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">Date</th>
                                            <th scope="col">Description</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for history in histories %}
                                            <tr>
                                                <td>{{ history['date'].strftime('%d/%m/%Y') }}</td>
                                                <td>{{ history['description'] }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <a class="btn btn-info btn-block" href="{{ url_for('history.index') }}">View More</a>
                            {% else %}
                                <h6>You do not have any Medical History Yet.</h6>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}