heartphoria/blueprints/appointment.py
from datetime import datetime

from flask import Blueprint, g, render_template, request, url_for, redirect

from heartphoria import db, redirect
from heartphoria.models import Appointment, Hospital
from heartphoria.blueprints.auth import login_required

blueprint = Blueprint('appointment', __name__, url_prefix='/appointment')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
    date = None
    time = None
    date_time = None
    location = None
    errors = {}

    if request.method == 'POST':
        delete = request.form.get('delete')

        if delete:
            appointment = Appointment.query.get(delete)
            db.session.delete(appointment)
            db.session.commit()
        else:
            date = request.form.get('date')
            time = request.form.get('time')
            location = request.form.get('location')

            if not (date and time):
                if not date:
                    errors['date'] = 'Date is required.'

                if not time:
                    errors['time'] = 'Time is required.'
            else:
                date_time = datetime.strptime(date + ' ' + time, '%Y-%m-%d %H:%M')

            if not location:
                errors['location'] = 'Location is required.'

            if not errors:
                appointment = Appointment(user_id=g.user['id'], date_time=date_time, location=location) #create appointment object with user input value
                db.session.add(appointment)
                db.session.commit()

                return redirect(url_for('.index'))

    appointments = Appointment.query.filter_by(user_id=g.user['id']).order_by(Appointment.date_time.desc()).all() #retrieve all appointment data based on user id
    hospitals = Hospital.query.with_entities(Hospital.name).all()

    return render_template('appointment/index.html', date=date, time=time, location=location, errors=errors, appointments=appointments, autocomplete=hospitals)

heartphoria/blueprints/auth.py
import functools
import re
import random
import string

import requests
from flask import Blueprint, g, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from heartphoria import db, ngrok_url, redirect
from heartphoria.models import User
from heartphoria.mail import Mail

blueprint = Blueprint('auth', __name__)


@blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
    name = None
    email = None
    errors = {}

    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm = request.form.get('confirm')

        if not name:
            errors['name'] = 'Name is required.'
        elif not re.match(r'[a-zA-Z]+(?:\s[a-zA-Z]+)*$', name):
            errors['name'] = 'Name is invalid'

        if not email:
            errors['email'] = 'Email is required.'
        elif not re.match(r"[a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", email):
            errors['email'] = 'Email is invalid.'
        elif User.query.filter_by(email=email.lower()).first() is not None:
            errors['email'] = email + ' already exists'

        if not password:
            errors['password'] = 'Password is required.'
        elif not re.match(r'(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$', password):
            errors['password'] = 'Password is invalid'
        elif not confirm:
            errors['confirm'] = 'Please re-enter password for confirmation'
        elif not password == confirm:
            errors['confirm'] = 'Passwords do not match'

        if not errors:
            user = User(email=email.lower(), password=generate_password_hash(password), name=name, role='user')
            db.session.add(user)
            db.session.commit()

            Mail().send_mail(
                email,
                '[Heartphoria] Sign Up Successful',
                render_template('email/signup.html', name=name, email=email.lower(), password=password)
            )

            return redirect(url_for('.login'))

    return render_template('auth/signup.html', title='Sign up', name=name, email=email, errors=errors)


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    email = None
    errors = {}

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        if not email:
            errors['email'] = 'Email is required'
        else:
            user = User.query.filter_by(email=email.lower()).first()

            if user is None:
                errors['email'] = email + ' does not exist'
            elif not check_password_hash(user.password, password):
                errors['password'] = 'Password is incorrect'

        if not errors:
            session.clear()
            session['user_id'] = user.id

            return redirect(url_for('general.index'))

    return render_template('auth/login.html', title='Login', email=email, errors=errors)


@blueprint.route('/forgot', methods=['GET', 'POST'])
def forgot():
    email = None
    errors = {}

    if request.method == 'POST':
        link = None
        email = request.form.get('email')

        if not email:
            errors['email'] = 'Email is required'
        else:
            user = User.query.filter_by(email=email.lower()).first()

            if user is None:
                errors['email'] = email + ' is not registered'
            else:
                fcode = ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.digits) for _ in range(8))

                user.fcode = fcode
                db.session.commit()

                # Determines if ngrok is up.
                try:
                    if requests.get(ngrok_url, timeout=1).status_code == 200:
                        print('ngrok is up, using %s URL instead...' % ngrok_url)

                        link = ngrok_url + '/change/' + str(user.id) + '/' + fcode
                except requests.exceptions.ConnectionError:
                    print('ngrok is not up, using localhost URL instead...')

                    if link is None:
                        link = request.url_root + 'change/' + str(user.id) + '/' + fcode
                except requests.exceptions.RequestException as e:
                    print(e)

                Mail().send_mail(
                    email,
                    '[Heartphoria] Forgot Password',
                    render_template('email/forgot.html', link=link)
                )

                return render_template('auth/forgot_success.html')

    return render_template('auth/forgot.html', title='Forgot Password', email=email, errors=errors)


@blueprint.route('/forgot/<int:user_id>')
def resend_forgot(user_id):
    link = None

    user = User.query.filter_by(id=user_id).first()

    if user is None:
        return redirect(url_for('auth.forgot'))
    else:
        fcode = ''.join(random.SystemRandom().choice(string.ascii_lowercase + string.digits) for _ in range(8))

        user.fcode = fcode
        db.session.commit()

        # Determines if ngrok is up.
        try:
            if requests.get(ngrok_url, timeout=1).status_code == 200:
                print('ngrok is up, using %s URL instead...' % ngrok_url)

                link = ngrok_url + str(user.id) + '/' + fcode
        except requests.exceptions.ConnectionError:
            print('ngrok is not up, using localhost URL instead...')

            if link is None:
                link = request.url_root + 'change/' + str(user.id) + '/' + fcode
        except requests.exceptions.RequestException as e:
            print(e)

        Mail().send_mail(
            user.email,
            '[Heartphoria] Forgot Password',
            render_template('email/forgot.html', link=link)
        )

    return render_template('auth/forgot_success.html')


@blueprint.route('/change/<int:user_id>/<string:fcode>', methods=['GET', 'POST'])
def change(user_id, fcode):
    errors = {}

    user = User.query.filter_by(id=user_id, fcode=fcode).first()

    if user is None:
        return render_template('auth/change_error.html', user_id=user_id)

    if request.method == 'POST':
        password = request.form.get('password')
        confirm = request.form.get('confirm')

        if not password:
            errors['password'] = 'Password is required'
        elif not re.match(r'(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$', password):
            errors['password'] = 'Password is invalid'
        elif not confirm:
            errors['confirm'] = 'Please re-enter password for confirmation'
        elif not password == confirm:
            errors['confirm'] = 'Passwords do not match'

        if not errors:
            user.password = generate_password_hash(password)
            user.fcode = None
            db.session.commit()

            Mail().send_mail(
                user.email,
                '[Heartphoria] Password Changed',
                render_template('email/change.html', password=password)
            )

            return render_template('auth/change_success.html', title='Change Password Successful')

    return render_template('auth/change.html', title='Change Password', errors=errors)


@blueprint.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        user = User.query.filter_by(id=user_id).first()

        if user:
            user = user.__dict__

            if '_sa_instance_state' in user:
                del user['_sa_instance_state']

            g.user = user


@blueprint.route('/logout')
def logout():
    session.clear()

    return redirect(url_for('general.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

heartphoria/blueprints/reminder.py
from datetime import datetime

from flask import Blueprint, g, render_template, request, url_for

from heartphoria import db, redirect
from heartphoria.models import Reminder
from heartphoria.blueprints.auth import login_required

blueprint = Blueprint('reminder', __name__, url_prefix='/reminder')


@blueprint.route('/', methods=['GET', 'POST'])
@login_required
def index():
    time = None
    medication = None
    quantity = None
    errors = {}

    if request.method == 'POST':
        delete = request.form.get('delete')

        if delete:
            reminder = Reminder.query.get(delete)
            db.session.delete(reminder)
            db.session.commit()

            return redirect(url_for('.index'))
        else:
            time = request.form.get('time')
            medication = request.form.get('medication')
            quantity = request.form.get('quantity')

            if not time:
                errors['time'] = 'Time is required.'
            else:
                time = datetime.strptime(time, '%H:%M').time().isoformat()

            if not medication:
                errors['medication'] = 'Medication is required.'

            if not quantity:
                errors['quantity'] = 'Quantity is required.'

            if not errors:
                reminder = Reminder(user_id=g.user['id'], time=datetime.strptime(time, '%H:%M:%S').time(), medication=medication, quantity=quantity)
                db.session.add(reminder)
                db.session.commit()

                return redirect(url_for('.index'))

    reminders = Reminder.query.filter_by(user_id=g.user['id']).all()

    return render_template('reminder/index.html', title='Medication Reminder', time=time, medication=medication, quantity=quantity, errors=errors, reminders=reminders)

heartphoria/templates/index_state/guest_index.html
<div class="card acrylic shadow mt-4">
    <img class="card-img-top" src="{{ url_for('static', filename='images/background/med_reminder_header_bg.png') }}" alt="Medication Reminder">

    <div class="card-body">
        <h4 class="pb-3 text-primary">Medication Reminder</h4>
        <p>
            With Heartphoria you would never have to worry about forgetting to take your medication on time ever again.
        </p>
        <a class="btn btn-success btn-block" href="{{ url_for('auth.signup') }}">Sign Up</a>
    </div>
</div>

<div class="card acrylic shadow mt-4">
    <img class="card-img-top" src="{{ url_for('static',filename='images/background/med_schedule_header_bg.png') }}">

    <div class="card-body">
        <h4 class="pb-3 text-primary">Medical Appointment</h4>
        <p>
            With Heartphoria you would never forget your medical appointment again.
        </p>
        <a class="btn btn-success btn-block" href="{{ url_for('auth.signup') }}">Sign Up</a>
    </div>
</div>

heartphoria/templates/index_state/user_index.html
<div class="card acrylic shadow mt-4">
    <div class="card-body">
        <h4 class="pb-3 text-primary">Upcoming Medication Reminder</h4>

        {% if reminders %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Time</th>
                        <th scope="col">Medication</th>
                        <th scope="col">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    {% for reminder in reminders %}
                        <tr>
                            <td>{{ reminder['time'].strftime('%I:%m %p') }}</td>
                            <td>{{ reminder['medication'] }}</td>
                            <td>{{ reminder['quantity'] }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a class="btn btn-info btn-block" href="{{ url_for('reminder.index') }}">View More</a>
        {% else %}
            <h6>You do not have any Upcoming Medication Reminder Yet.</h6>
        {% endif %}
    </div>
</div>

<div class="card acrylic shadow mt-4">
    <div class="card-body">
        <h4 class="pb-3 text-primary">Upcoming Medical Appointment</h4>

        {% if appointments %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                        <th scope="col">Hospital / Clinic</th>
                    </tr>
                </thead>
                <tbody>
                    {% for appointment in appointments %}
                        <tr>
                            <td>{{ appointment['date_time'].strftime('%d/%m/%Y') }}</td>
                            <td>{{ appointment['date_time'].strftime('%I:%M %p') }}</td>
                            <td>{{ appointment['location'] }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a class="btn btn-info btn-block" href="{{ url_for('appointment.index') }}">View More</a>
        {% else %}
            <h6>You do not have any Upcoming Medical Appointment Yet.</h6>
        {% endif %}
    </div>
</div>